# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

name: CI/CD

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on shell scripts
        run: |
          ./shell-lint.sh

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install codespell
        run: pip install --upgrade pip && pip install codespell

      - name: Run codespell-lint
        run: |
          ./codespell-lint.sh
